# -*- coding: utf-8 -*-
"""problem1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J4qm1MxGu2NTz5xNMxZ49HxqtmO442Fx
"""

def palindrome(word):
  if word == " ":
    return "Not Palindrome"
  N = len(word)
  i = 0
  for i in range(N//2):
    if word[i] != word[N-1-i]:
      return "Not Palindrome"
    i = i + 1
  return "is Palindrome"

def parity(number):
    if "."in number:
      return "Cannot Have Parity"
    if int(number) % 2 == 0:
      return "Even Parity"
    else:
      return "Odd Parity"

print(palindrome("madam"))
print(parity("12.34"))