# -*- coding: utf-8 -*-
"""problem4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PvVpe4rEL90tmJJeNbMmkizgrjhMUpWG
"""

def Multiply_matrix(A,B):
    C = [[0,0],[0,0]]
             
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                C[i][j] += A[i][k] * B[k][j]

    for r in C:
        print(r)
        
A = [[12,44],[24,19]]    
B = [[55,11],[15,57]]


#There are three For loop in the code, we know for each for loop the time complexity is O(n).
#Therefore, the time complexity of the above code will be n*n*n = O(n^3).